using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Microcharts
{
    public abstract class SeriesChart : Chart
    {
        protected IEnumerable<ChartSerie> series;

        public IEnumerable<ChartSerie> Series
        {
            get => series;
            set => UpdateSeries(value);
        }

        protected virtual void UpdateSeries(IEnumerable<ChartSerie> value)
        {
            Set(ref series, value);
            UpdateEntries(series.SelectMany(s => s.Entries).ToList());
        }

        public IEnumerable<ChartEntry> Entries
        {
            get => entries;
            set => GenerateDefaultSerie(value);
        }

        protected bool IsSeriesAutoGenerated { get; private set; }

        protected virtual void GenerateDefaultSerie(IEnumerable<ChartEntry> value)
        {
            UpdateSeries(new ChartSerie[]
            {
                new ChartSerie()
                {
                    Entries = value.ToList(),
                    Name = "Default - AutoGenerated",
                    Color = null
                }
            });
            IsSeriesAutoGenerated = true;
        }
    }
}
