name: Microcharts PR Build
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Build for PR"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-26]
    steps:
      - name: Clone source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x

      - name: "Install .NET workloads"
        run: |
          dotnet workload install android
          dotnet workload install ios
          dotnet workload install maccatalyst
          dotnet workload install maui
          dotnet workload list

      - name: Select Xcode
        if: matrix.os == 'macos-26'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3'

      - name: "Build solution"
        run: dotnet build Sources/Microcharts.Maui.sln --configuration Release

      - name: "Pack Microcharts Core"
        run: dotnet pack Sources/Microcharts/Microcharts.csproj --configuration Release --no-build

      - name: "Pack Microcharts Droid"
        run: dotnet pack Sources/Microcharts.Droid/Microcharts.Droid.csproj --configuration Release --no-build

      - name: "Pack Microcharts iOS"
        run: dotnet pack Sources/Microcharts.iOS/Microcharts.iOS.csproj --configuration Release --no-build

      - name: "Pack Microcharts MAUI"
        run: dotnet pack Sources/Microcharts.Maui/Microcharts.Maui.csproj --configuration Release --no-build

      - name: "Pack Microcharts Meta-package"
        run: dotnet pack Sources/Microcharts.Metapackage/Microcharts.Metapackage.csproj --configuration Release
